import { initHeroSection } from "./scripts/heroSection.js";
import { initDestinations } from "./scripts/destinations.js";
import { initFeaturedTours } from "./scripts/featuredTours.js";
import { initCategoryTours } from "./scripts/categoryTours.js";
import { initNextTrip } from "./scripts/nextTrip.js";
import { initBannerAds } from "./scripts/bannerAds.js";
import { initInstallApp } from "./scripts/installApp.js";
import { initEasyPayment } from "./scripts/easyPayment.js";
import { initWhyTravila } from "./scripts/whyTravila.js";
import { initTrendingDestinations } from "./scripts/trendingDestinations.js";
import { initPrinciples } from "./scripts/principles.js";
import { initFilterCards } from "./scripts/filterCards.js";
import { initFooter } from "./scripts/footer.js";
import { initChatbot } from "./scripts/chatbot.js";

document.addEventListener("DOMContentLoaded", () => {
  initHeroSection();
  initDestinations();
  initFeaturedTours();
  initCategoryTours();
  initNextTrip();
  initBannerAds();
  initInstallApp();
  initEasyPayment();
  initWhyTravila();
  initTrendingDestinations();
  initPrinciples();
  initFilterCards();
  initFooter();
  initChatbot();
});
